apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${STATIC_IP_NAME}
  labels:
    app: grafana
spec:
  defaultBackend:
    service:
      name: grafana
      port:
        number: 3000
