apiVersion: v1
kind: ConfigMap
metadata:
  name: ge-logs-config
data:
  config.yaml: |-
    auth:
      type: enterprise

    target: all

    cluster_name: ${GEL_CLUSTER_NAME}

    license:
      path: /etc/ge-logs/license/license.jwt

    ingester:
      lifecycler:
        num_tokens: 512
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3

    # Configures how the Grafana Enterprise Logs Admin API service connects to the storage backend.
    admin_client:
      storage:
        type: gcs
        gcs:
          bucket_name: ${GCP_BUCKET_NAME_ADMIN}
          service_account: |
            ${GCP_SERVICE_ACCOUNT_JSON}

    chunk_store_config:
      max_look_back_period: 0s

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
        - ge-logs-discovery

    # Configures one of many possible stores for both the index and chunks. 
    storage_config:
      gcs:
        bucket_name: ${GCP_BUCKET_NAME_DATA}
      # boltdb-shipper stores boltdb index files in the object store
      boltdb_shipper:
        active_index_directory: /data/boltdb-shipper-active
        cache_location: /data/boltdb-shipper-cache
        cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: gcs

    schema_config:
      configs:
        - from: 2021-01-01
          store: boltdb-shipper
          object_store: gcs
          schema: v11
          index:
            prefix: index_
            period: 24h

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    compactor:
      working_directory: /data/boltdb-shipper-compactor
      shared_store: gcs
